language: php

jobs:
  include:
    - name: PHP 5.4
      php: 5.4
      dist: trusty
    - name: PHP 5.5
      php: 5.5
      dist: trusty
    - name: PHP 5.6
      php: 5.6
      dist: xenial
    - name: PHP 7.0
      php: 7.0
      dist: xenial
    - name: PHP 7.1
      php: 7.1
      dist: bionic
    - name: PHP 7.2
      php: 7.2
      dist: bionic
    - name: PHP 7.3
      php: 7.3
      dist: bionic
    - name: PHP 7.4
      php: 7.4
      dist: bionic
    - name: PHP 8.0
      php: 8.0
      dist: bionic

before_script:
  - composer self-update
  - composer install --dev

script: ./vendor/bin/phpunit -c lib/ --coverage-text

notifications:
  email:
    - ruben@codeforges.com
    - david.djian@traceweb.fr
